/* eslint-disable */
const log = require('@colmena/logger')

log.yellow.b('┌───────────────────────────────────────────────────────────────────────────────────────────────────┐')
log.yellow.b('│           _____                                                                                   │')
log.yellow.b('│          ╱     ╲    Colmena is Free and Open Source Software licensed under the MIT License       │')
log.yellow.b('│    _____╱       ╲                                                                                 │')
log.yellow.b('│   ╱     ╲       ╱   If you like Colmena and would like to support its development please consider │')
log.yellow.b('│  ╱       ╲_____╱    becoming a Sponsor or a Backer of our project via our OpenCollective page     │')
log.yellow.b('│  ╲       ╱     ╲                                                                                  │')
log.yellow.b('│   ╲_____╱       ╲   https://opencollective.com/colmena                                            │')
log.yellow.b('│         ╲       ╱   https://opencollective.com/colmena/donate                                     │')
log.yellow.b('│          ╲_____╱                                                                                  │')
log.yellow.b('│                                                                                                   │')
log.yellow.b('└───────────────────────────────────────────────────────────────────────────────────────────────────┘')
log.magenta.b(`┌───────────────────────────────────────────────────────────────────────────────────────────────────┐`)
log.magenta.b(`│ [!] Colmena's dependencies are installed.                                                         │`)
log.magenta.b(`│ [!] Please run 'lerna bootstrap' to link the local dependencies                                   │`)
log.magenta.b(`└───────────────────────────────────────────────────────────────────────────────────────────────────┘`)
